from .tables.ArtistsTracks import ArtistsTracks
from .tables.AlbumsArtists import AlbumsArtists
from .tables.Artists import Artists
from .tables.Featurings import Featurings
from .tables.Albums import Albums
from .tables.Singles import Singles
from .tables.Tracks import Tracks
from .tables.AlbumsTracks import AlbumsTracks
from .tables.Products import Products
from .tables.Lyrics import Lyrics
from .tables.Genres import Genres
from .tables.Keys import Keys
from .tables.Beats import Beats
from .tables.Mixing import Mixing
from .tables.Mastering import Mastering
from .tables.MixingAndMastering import MixingAndMastering
from .tables.Ghostwriting import Ghostwriting
